### PR TITLE
Fix for #73

### PR DESCRIPTION
**Pull request by florisk**
I choose to move the $handle to the static class member $log_handle.
This would seem to have the least impact on the code.
Perhaps a non-static member might be better.

I also added a test case for review purposes.

### CODE REVIEW

**Comment by shaneharter** [comment]
thank you for your work! this library could use TLC. Unfortunately I've not been able to devote time to it lately.

**Comment by florisk** [comment]
You're welcome. What do you mean by TLC ? The test case ? 
I used the test case to analyze the cause and test the fix. This test would make it easier for you to evaluate and test the fix so there was no point in not checking it in.

The test case also creates some other static streams which do not get closed, 
but I found no way to close them.

**Comment by shaneharter** [comment]
TLC is an American saying meaning that it needs attention and work. Thank
you again for your help and for the test case

**Comment by florisk** [comment]
I see, thanks for the clarification.

**Pull request merged**
